[workspace]
members = [
    "programs/*",
    "tests/hosted",
    "tests/mock-adapter",
    "libraries/rust",
    "libraries/static-program-registry",
]

[patch.crates-io]
jet-proto-math = { git = "https://github.com/jet-lab/program-libraries", branch = "main" }